### ISSUE TITLE
sap-cloud-sdk init fails

### ISSUE THREAD

**Issue by bertdeterd** [SAP/cloud-sdk-cli#17]
I must be doing something wrong but I get this error:

Reading templates... !
TypeError: curr.isDirectory is not a function
    at files.reduce (C:/Users/bertd/AppData/Roaming/npm/node_modules/@sap-cloud-sdk/cli/lib/utils/templates.js:15:18)
    at Array.reduce (<anonymous>)
    at Object.readTemplates (C:/Users/bertd/AppData/Roaming/npm/node_modules/@sap-cloud-sdk/cli/lib/utils/templates.js:14:18)   
    at Init.run (C:/Users/bertd/AppData/Roaming/npm/node_modules/@sap-cloud-sdk/cli/lib/commands/init.js:22:39)
    at <anonymous>

version:
@sap-cloud-sdk/cli/0.0.6 win32-x64 node-v8.9.4

**Comment by bertdeterd** [comment]
sorry about this. Updated NodeJS.
